#ifndef ERRORS_H_
#define ERRORS_H_

#define INVALID_NAME 1
#define INVALID_EXECUTION_NAME 2
#define INVALID_RESULT 3
#define SUCCEEDED 0
#define INVALID_EXE_FILE 5
#define INVALID_PARAMETERS 6
#define DEAD_LOCK_OR_FILES_ABSENT_WAS_FOUND 7
#define EXE_OR_XML_ABSENT 8
#define WRONG_PATH_EXECUTION 9
#define WRONG_WAITFOR 10

#endif