alert("Hello from main siute!");
Box.StartApp("C:/Windows/SYSTEM32/mspaint.exe");
Box.SetOnTop("Untitled - Paint");
Box.WindowMinimize();
Box.Sleep(500);
Box.WindowMaximize();
Box.Sleep(500);
Box.WindowRestore();
Box.Sleep(500);
Box.WindowMaximize();
Box.Sleep(500);
Box.SetMousePos(300,300);
Box.MouseDown(0);
Box.MouseMove(600,600, 5);
Box.MouseUp(0);
Box.CloseApp();
Box.PrintScreen("D:/1.jpg");
alert(Test.GetData("printscreen"));
Box.Log('Hello from main siute!');