alert("Hello from main siute!");
core.StartApp("C:/Windows/SYSTEM32/mspaint.exe");
core.SetOnTop("Untitled - Paint");
core.WindowMinimize();
core.Sleep(500);
core.WindowMaximize();
core.Sleep(500);
core.WindowRestore();
core.Sleep(500);
core.WindowMaximize();
core.Sleep(500);
core.SetMousePos(300,300);
core.MouseDown(0);
core.MouseMove(600,600, 5);
core.MouseUp(0);
core.CloseApp();
core.PrintScreen("D:/1.jpg");
alert(Test.GetData("printscreen"));
trs.writeMSG('Hello from main siute!');